import type { ContentBundleInput } from '../src/lib/content-bundle'

/**
 * Prompts do seed. O corpo fica em inglês (melhor aderência na maioria dos modelos);
 * explicações em português. Variáveis no formato {{chave}}.
 */
export const prompts: NonNullable<ContentBundleInput['prompts']> = [
  {
    slug: 'luxury-product-photography-studio-campaign',
    title: 'Luxury Product Photography — Studio Campaign',
    category: 'produtos',
    difficulty: 'INTERMEDIATE',
    featured: true,
    summary: 'Fotografia comercial de produto com luz de estúdio dramática, pronta para campanha de marca premium.',
    description:
      'Este prompt foi criado para gerar fotografias comerciais de produtos com iluminação de estúdio: fundo escuro, luz de recorte que desenha o contorno e reflexos controlados. Funciona para perfumes, relógios, cosméticos, bebidas e eletrônicos. Troque o produto e o material de destaque para adaptar à sua marca.',
    mediaType: 'IMAGE',
    aspectRatio: '4:5',
    body: 'High-end commercial product photograph of {{produto}}, placed on a {{superficie}} in a dark studio. Dramatic rim light tracing the silhouette, soft key light from the upper left, controlled specular highlights on {{material}}. Subtle {{cor_destaque}} accent light in the background, fine haze, deep blacks. Centered hero composition with generous negative space above. Shot on a 100mm macro lens, f/8, razor-sharp focus, luxury advertising aesthetic, ultra-detailed, photorealistic.',
    negativePrompt: 'text, watermark, logo distortion, extra objects, clutter, fingerprints, dust, low contrast, overexposed highlights, cartoon, illustration',
    variables: [
      { key: 'produto', label: 'Produto', placeholder: 'a matte black perfume bottle with a gold cap', description: 'Descreva forma, cor e material principal.' },
      { key: 'superficie', label: 'Superfície', placeholder: 'polished black marble podium', defaultValue: 'polished black marble podium' },
      { key: 'material', label: 'Material em destaque', placeholder: 'the glass and brushed gold details', defaultValue: 'the glass and metal details' },
      { key: 'cor_destaque', label: 'Cor de destaque', placeholder: 'warm gold', defaultValue: 'warm gold' },
    ],
    parameters: [
      { label: 'Midjourney', value: '--ar 4:5 --style raw --stylize 250' },
      { label: 'Proporção', value: '4:5 (feed) ou 9:16 (stories)' },
    ],
    recommendedSettings: [
      { label: 'Variações', value: 'Gere 4 e escolha pela luz, não pelo produto' },
      { label: 'Upscale', value: 'Magnific com criatividade baixa (0–2) para não alterar o rótulo' },
    ],
    expectedResult: 'Imagem de produto com aparência de campanha: fundo escuro, contorno iluminado, reflexos limpos e espaço livre para inserir logo ou headline depois.',
    tips: [
      'Descreva o produto como um fotógrafo descreveria: forma, material, acabamento.',
      'Rótulos e logos raramente saem perfeitos — aplique a marca real na pós-produção.',
      'Mude apenas a cor de destaque para criar uma série consistente de peças.',
    ],
    tools: ['midjourney', 'chatgpt-gpt-image', 'magnific-ai'],
    tags: ['produto', 'estúdio', 'luxo', 'campanha', 'e-commerce'],
    related: ['REFERENCE:chiaroscuro-para-perfumaria-de-luxo', 'WORKFLOW:foto-de-produto-para-video-comercial', 'TUTORIAL:iluminacao-para-fotografia-de-produto-com-ia'],
  },
  {
    slug: 'cinematic-fitness-campaign',
    title: 'Cinematic Fitness Campaign',
    category: 'cinematico',
    difficulty: 'ADVANCED',
    featured: true,
    summary: 'Cena cinematográfica de treino com suor, luz dura e câmera lenta — base para anúncios de academia.',
    description:
      'Prompt de vídeo para campanhas de academia, suplementos e roupas esportivas. Descreve ação, câmera e luz como um diretor de fotografia. Use com imagem inicial para manter o atleta consistente.',
    mediaType: 'VIDEO',
    aspectRatio: '9:16',
    body: 'Cinematic slow-motion shot of {{atleta}} performing {{exercicio}} in a dark industrial gym. Hard top light and a single cool rim light from behind, sweat droplets catching the light, chalk dust floating in the air. Camera: low angle, slow push-in, shallow depth of field, anamorphic lens flare. Color grade: deep blacks, desaturated skin tones, {{cor}} highlights. Mood: relentless, focused, powerful. 24fps film look, subtle grain.',
    negativePrompt: 'distorted limbs, extra fingers, morphing face, text, logos, cartoon, jittery camera, low detail',
    variables: [
      { key: 'atleta', label: 'Atleta', placeholder: 'a muscular woman in black training gear', defaultValue: 'an athletic man in black training gear' },
      { key: 'exercicio', label: 'Exercício', placeholder: 'a heavy deadlift', defaultValue: 'battle rope slams' },
      { key: 'cor', label: 'Cor de destaque', placeholder: 'electric blue', defaultValue: 'warm amber' },
    ],
    parameters: [
      { label: 'Duração', value: '5 a 8 segundos por clipe' },
      { label: 'Proporção', value: '9:16 para Reels/TikTok' },
    ],
    recommendedSettings: [
      { label: 'Modo', value: 'Imagem para vídeo, com um frame gerado antes no Midjourney' },
      { label: 'Movimento', value: 'Baixo a médio — movimento demais deforma o corpo' },
    ],
    expectedResult: 'Clipe vertical de alta energia com estética de comercial esportivo, pronto para receber trilha e texto.',
    tips: [
      'Gere primeiro a imagem do atleta e anime depois: a consistência melhora muito.',
      'Uma ação por clipe. Sequências complexas funcionam melhor como cortes separados.',
      'Descreva a câmera (ângulo, movimento, lente) — é o que dá cara de cinema.',
    ],
    tools: ['kling-ai', 'runway', 'google-veo'],
    tags: ['fitness', 'academia', 'vídeo', 'anúncio', 'câmera lenta'],
    related: ['WORKFLOW:anuncio-completo-para-academia', 'REFERENCE:neon-noir-urbano-esportivo', 'TUTORIAL:direcao-de-camera-em-video-com-ia'],
  },
  {
    slug: 'editorial-fashion-portrait',
    title: 'Editorial Fashion Portrait',
    category: 'moda',
    difficulty: 'INTERMEDIATE',
    summary: 'Retrato de moda com linguagem de revista: pose intencional, luz suave e styling em destaque.',
    description:
      'Gera retratos editoriais para lookbooks, campanhas de coleção e posts de marca de moda. O foco é o styling e a atitude, com luz de janela e fundo minimalista.',
    mediaType: 'IMAGE',
    aspectRatio: '4:5',
    body: 'Editorial fashion portrait of {{modelo}} wearing {{look}}, standing against a {{fundo}}. Soft window light from the side, gentle falloff, natural skin texture with visible pores. Confident, slightly detached expression, three-quarter body framing, intentional pose with elongated lines. Shot on medium format, 80mm lens, f/4. Muted palette, magazine cover quality, minimal styling of the set.',
    negativePrompt: 'plastic skin, over-retouched, extra fingers, warped fabric, busy background, text, watermark',
    variables: [
      { key: 'modelo', label: 'Modelo', placeholder: 'a Brazilian woman with short curly hair', defaultValue: 'a model with sharp features' },
      { key: 'look', label: 'Look', placeholder: 'an oversized camel wool coat and wide-leg trousers' },
      { key: 'fundo', label: 'Fundo', placeholder: 'seamless off-white paper backdrop', defaultValue: 'seamless off-white paper backdrop' },
    ],
    parameters: [{ label: 'Midjourney', value: '--ar 4:5 --style raw --stylize 150' }],
    recommendedSettings: [{ label: 'Referência de estilo', value: 'Use uma imagem da coleção real como referência de estilo' }],
    expectedResult: 'Retrato de moda limpo, com textura de pele natural e o look como protagonista.',
    tips: ['Descreva o tecido e o caimento da roupa — é o que torna o look crível.', '“Natural skin texture” evita a pele plástica típica de IA.'],
    tools: ['midjourney', 'magnific-ai'],
    tags: ['moda', 'editorial', 'retrato', 'lookbook'],
    related: ['WORKFLOW:ensaio-editorial-de-moda-com-ia', 'REFERENCE:editorial-minimalista-off-white'],
  },
  {
    slug: 'ai-product-advertisement-hero-banner',
    title: 'AI Product Advertisement — Hero Banner',
    category: 'criar-anuncios',
    difficulty: 'BEGINNER',
    featured: true,
    summary: 'Banner publicitário com produto em destaque e headline legível na própria imagem.',
    description:
      'Prompt pensado para ferramentas que escrevem texto com precisão. Gera um banner completo — produto, cenário e headline — para testes rápidos de criativo em anúncios.',
    mediaType: 'IMAGE',
    aspectRatio: '16:9',
    body: 'Professional advertising banner for {{marca}}. {{produto}} as the hero on the right side, dynamic angle, floating slightly with a soft shadow. Background: {{cenario}}. On the left, bold clean sans-serif headline that reads exactly "{{headline}}", with a smaller subline "{{subheadline}}" below. Balanced layout, clear visual hierarchy, premium commercial lighting, high contrast, ready for a paid social ad.',
    negativePrompt: 'misspelled text, extra words, cluttered layout, low resolution, distorted product',
    variables: [
      { key: 'marca', label: 'Marca', placeholder: 'a premium coffee brand' },
      { key: 'produto', label: 'Produto', placeholder: 'a matte black coffee bag with copper details' },
      { key: 'cenario', label: 'Cenário', placeholder: 'warm gradient from espresso brown to cream, coffee beans in motion', defaultValue: 'clean dark gradient with subtle light rays' },
      { key: 'headline', label: 'Headline', placeholder: 'Acorde com intenção' },
      { key: 'subheadline', label: 'Subheadline', placeholder: 'Torra artesanal, entrega em 24h' },
    ],
    parameters: [{ label: 'Proporção', value: '16:9 (banner), 1:1 ou 4:5 (feed)' }],
    recommendedSettings: [{ label: 'Texto', value: 'Headlines curtas (até 5 palavras) têm muito mais acerto' }],
    expectedResult: 'Banner pronto para teste A/B, com produto, headline e subline legíveis.',
    tips: ['Coloque o texto exato entre aspas.', 'Gere o banner e refaça apenas o texto se necessário, pedindo ajustes pontuais.'],
    tools: ['chatgpt-gpt-image', 'ideogram'],
    tags: ['anúncio', 'banner', 'tipografia', 'tráfego pago'],
    related: ['WORKFLOW:lancamento-de-produto-no-instagram'],
  },
  {
    slug: 'instagram-product-launch-carousel',
    title: 'Instagram Product Launch — Carousel Cover',
    category: 'social-media',
    difficulty: 'BEGINNER',
    summary: 'Capa de carrossel para lançamento de produto, com composição que pede o “arrasta pro lado”.',
    description:
      'Gera a primeira imagem de um carrossel de lançamento: produto parcialmente revelado, cor forte e espaço para título. Crie os demais slides mantendo o mesmo cenário.',
    mediaType: 'IMAGE',
    aspectRatio: '4:5',
    body: 'Instagram carousel cover for a product launch. {{produto}} partially cropped by the right edge of the frame, suggesting continuation to the next slide. Solid {{cor}} background with a soft gradient, playful hard shadow, glossy highlights. Top-left area left clean for a title. Bold, modern, scroll-stopping, commercial product photography, 4:5 vertical.',
    variables: [
      { key: 'produto', label: 'Produto', placeholder: 'a pastel pink wireless earbud case, open' },
      { key: 'cor', label: 'Cor de fundo', placeholder: 'tangerine orange', defaultValue: 'vivid cobalt blue' },
    ],
    parameters: [{ label: 'Midjourney', value: '--ar 4:5 --stylize 200' }],
    recommendedSettings: [{ label: 'Série', value: 'Reutilize o mesmo seed/referência para os slides seguintes' }],
    expectedResult: 'Capa de carrossel com alto contraste e continuidade visual para o próximo slide.',
    tips: ['Carrosséis com cor sólida e produto cortado aumentam o “arrasta”.', 'Aplique o título no Canva/Figma para controle total.'],
    tools: ['midjourney', 'chatgpt-gpt-image'],
    tags: ['instagram', 'carrossel', 'lançamento', 'produto'],
    related: ['WORKFLOW:lancamento-de-produto-no-instagram'],
  },
  {
    slug: 'luxury-restaurant-campaign',
    title: 'Luxury Restaurant Campaign',
    category: 'fotografia',
    difficulty: 'INTERMEDIATE',
    summary: 'Fotografia gastronômica dark & moody para restaurantes de alto padrão.',
    description:
      'Prompt para pratos autorais e drinks com estética de restaurante estrelado: luz lateral baixa, fundo escuro, vapor e texturas em evidência. Ideal para cardápio digital, Instagram e campanhas de inauguração.',
    mediaType: 'IMAGE',
    aspectRatio: '4:5',
    body: 'Fine dining food photography of {{prato}} plated on {{louca}}, on a dark walnut table. Low side light from a single window, deep shadows, delicate steam rising, glistening sauce, visible texture of every ingredient. Shallow depth of field, 90mm lens, f/2.8. Moody, intimate, Michelin-star restaurant atmosphere, subtle warm candle glow in the background bokeh.',
    negativePrompt: 'plastic food, oversaturated, messy plate, cutlery clutter, text, harsh flash',
    variables: [
      { key: 'prato', label: 'Prato', placeholder: 'seared scallops with pea purée and micro herbs' },
      { key: 'louca', label: 'Louça', placeholder: 'a handmade matte black ceramic plate', defaultValue: 'a handmade matte ceramic plate' },
    ],
    parameters: [{ label: 'Midjourney', value: '--ar 4:5 --style raw' }],
    expectedResult: 'Foto de prato com aparência premium, textura apetitosa e atmosfera intimista.',
    tips: ['Comida gerada por IA precisa de textura: cite brilho, crocância, vapor.', 'Use fotos reais do prato como referência para manter fidelidade ao cardápio.'],
    tools: ['midjourney', 'magnific-ai'],
    tags: ['gastronomia', 'restaurante', 'fotografia', 'dark moody'],
    related: ['WORKFLOW:campanha-para-restaurante-premium', 'REFERENCE:gastronomia-dark-and-moody'],
  },
  {
    slug: 'before-after-image-enhancement',
    title: 'Before & After Image Enhancement',
    category: 'melhorar-fotos',
    difficulty: 'BEGINNER',
    featured: true,
    summary: 'Instrução para restaurar e melhorar fotos reais mantendo a pessoa ou o produto fiel ao original.',
    description:
      'Use em ferramentas de edição por instrução para recuperar nitidez, corrigir luz e remover ruído sem “inventar” um rosto novo. Perfeito para conteúdo de antes e depois.',
    mediaType: 'IMAGE',
    body: 'Enhance this photo while keeping the subject 100% identical: same face, same proportions, same expression, same clothing. Restore sharpness and fine detail, remove noise and compression artifacts, correct white balance to {{temperatura}}, recover detail in shadows and highlights. {{ajuste_extra}}. Do not change the background composition, do not add or remove objects. Photorealistic, natural result.',
    variables: [
      { key: 'temperatura', label: 'Temperatura de cor', placeholder: 'neutral daylight', defaultValue: 'neutral daylight' },
      { key: 'ajuste_extra', label: 'Ajuste extra', placeholder: 'Add a subtle soft light on the face', defaultValue: 'Keep skin texture natural' },
    ],
    recommendedSettings: [
      { label: 'Upscale depois', value: 'Topaz para fidelidade; Magnific com criatividade ≤ 1 para detalhe' },
      { label: 'Resolução de entrada', value: 'Envie o arquivo original, não print de tela' },
    ],
    expectedResult: 'Mesma foto, mais nítida e bem iluminada — ideal para comparação lado a lado.',
    tips: ['Repita “keep identical” de formas diferentes: modelos tendem a embelezar.', 'Compare olhos e mãos antes de publicar — são onde a IA mais altera.'],
    tools: ['chatgpt-gpt-image', 'topaz-labs', 'magnific-ai'],
    tags: ['restauração', 'antes e depois', 'melhorar foto', 'upscale'],
    related: ['WORKFLOW:restauracao-e-melhoria-de-fotos', 'TUTORIAL:upscale-sem-artefatos'],
  },
  {
    slug: 'corporate-headshot-natural-light',
    title: 'Corporate Headshot — Natural Light',
    category: 'retratos',
    difficulty: 'BEGINNER',
    summary: 'Foto de perfil profissional com luz natural, fundo de escritório desfocado e expressão confiante.',
    description: 'Retrato corporativo para LinkedIn, site institucional e apresentações. Luz suave, fundo neutro e roupa alinhada à área de atuação.',
    mediaType: 'IMAGE',
    aspectRatio: '1:1',
    body: 'Professional corporate headshot of {{pessoa}}, wearing {{roupa}}. Soft natural window light, gentle fill, blurred modern office background with warm tones. Chest-up framing, eyes to camera, approachable confident smile. 85mm lens, f/2, natural skin texture, true-to-life colors, LinkedIn profile quality.',
    negativePrompt: 'plastic skin, heavy makeup, distorted teeth, harsh shadows, text',
    variables: [
      { key: 'pessoa', label: 'Pessoa', placeholder: 'a Brazilian man in his 40s with a short beard' },
      { key: 'roupa', label: 'Roupa', placeholder: 'a navy blazer over a white t-shirt', defaultValue: 'a navy blazer over a light shirt' },
    ],
    parameters: [{ label: 'Proporção', value: '1:1' }],
    expectedResult: 'Headshot natural e profissional, pronto para perfil.',
    tips: ['Para fotos da própria pessoa, use a foto real como referência de personagem.'],
    tools: ['midjourney', 'chatgpt-gpt-image'],
    tags: ['retrato', 'linkedin', 'corporativo'],
  },
  {
    slug: 'product-360-turntable-video',
    title: 'Product 360° Turntable Video',
    category: 'criar-videos',
    difficulty: 'INTERMEDIATE',
    summary: 'Animação de produto girando sobre base, com luz que desliza pela superfície.',
    description: 'Prompt de imagem-para-vídeo para transformar uma foto de produto em um giro elegante — ótimo para e-commerce, stories e anúncios.',
    mediaType: 'VIDEO',
    aspectRatio: '9:16',
    body: 'The product slowly rotates 180 degrees on a turntable, perfectly centered. Studio lighting stays fixed while highlights glide across its surface. Camera locked off, no zoom. The product shape, label and colors remain exactly the same throughout. Clean {{fundo}} background, soft floor reflection, smooth and elegant motion, premium commercial feel.',
    negativePrompt: 'morphing, warped label, shape change, camera shake, extra objects',
    variables: [{ key: 'fundo', label: 'Fundo', placeholder: 'deep charcoal gradient', defaultValue: 'deep charcoal gradient' }],
    parameters: [{ label: 'Duração', value: '5 segundos' }],
    recommendedSettings: [
      { label: 'Entrada', value: 'Foto do produto em alta resolução, fundo limpo' },
      { label: 'Movimento', value: 'Baixo; aumente só se o giro não acontecer' },
    ],
    expectedResult: 'Clipe curto com rotação suave e produto fiel à foto original.',
    tips: ['Rotações de 180° deformam menos que 360°.', 'Se o rótulo deformar, recorte o giro e use o trecho estável.'],
    tools: ['kling-ai', 'runway'],
    tags: ['produto', 'vídeo', 'e-commerce', 'animação'],
    related: ['WORKFLOW:foto-de-produto-para-video-comercial', 'TUTORIAL:animando-imagens-estaticas'],
  },
  {
    slug: 'cinematic-drone-establishing-shot',
    title: 'Cinematic Drone Establishing Shot',
    category: 'cinematico',
    difficulty: 'INTERMEDIATE',
    summary: 'Plano aéreo de abertura com movimento contínuo de drone e luz de hora dourada.',
    description: 'Plano de ambientação para abrir vídeos institucionais, imobiliários e de turismo. Movimento de drone suave com luz de fim de tarde.',
    mediaType: 'VIDEO',
    aspectRatio: '16:9',
    body: 'Cinematic aerial drone shot slowly gliding forward over {{local}} at golden hour. Long shadows, warm sunlight, light atmospheric haze, gentle parallax between foreground and background. Smooth continuous forward motion with a subtle tilt down revealing {{destaque}}. Shot on a cinema camera, natural color grade, 24fps.',
    variables: [
      { key: 'local', label: 'Local', placeholder: 'a coastal town with white houses and turquoise water' },
      { key: 'destaque', label: 'Revelação final', placeholder: 'a modern beach house with an infinity pool' },
    ],
    parameters: [{ label: 'Proporção', value: '16:9 (YouTube/institucional)' }],
    expectedResult: 'Plano aéreo fluido, com cara de abertura de filme institucional.',
    tips: ['Movimento contínuo e lento é mais crível que manobras rápidas.'],
    tools: ['google-veo', 'runway', 'kling-ai'],
    tags: ['drone', 'aéreo', 'vídeo', 'institucional'],
    related: ['TUTORIAL:direcao-de-camera-em-video-com-ia'],
  },
  {
    slug: 'brand-moodboard-generator',
    title: 'Brand Moodboard Generator',
    category: 'branding',
    difficulty: 'BEGINNER',
    summary: 'Moodboard de marca em grade: texturas, materiais, paleta e fotografia numa única imagem.',
    description: 'Gera um painel visual para alinhar a direção de uma marca antes de produzir peças. Ótimo para apresentar conceito a clientes.',
    mediaType: 'IMAGE',
    aspectRatio: '3:2',
    body: 'Brand moodboard for {{marca}}, a {{segmento}} brand. Grid layout of 9 tiles: material textures, product details, lifestyle photography, architectural details and a color palette swatch row of {{paleta}}. Mood: {{atmosfera}}. Cohesive art direction, editorial layout with thin gutters, clean off-white background, high-end design studio presentation.',
    variables: [
      { key: 'marca', label: 'Marca', placeholder: 'Aurora' },
      { key: 'segmento', label: 'Segmento', placeholder: 'sustainable skincare' },
      { key: 'paleta', label: 'Paleta', placeholder: 'sand, terracotta, sage green and off-white' },
      { key: 'atmosfera', label: 'Atmosfera', placeholder: 'calm, natural, honest', defaultValue: 'refined and calm' },
    ],
    parameters: [{ label: 'Midjourney', value: '--ar 3:2 --stylize 300' }],
    expectedResult: 'Painel coeso que comunica a direção visual da marca de uma vez.',
    tips: ['Gere 2 ou 3 moodboards com atmosferas diferentes para o cliente escolher.'],
    tools: ['midjourney', 'krea-ai'],
    tags: ['branding', 'moodboard', 'direção de arte'],
    related: ['REFERENCE:editorial-minimalista-off-white'],
  },
  {
    slug: '3d-isometric-product-scene',
    title: '3D Isometric Product Scene',
    category: '3d',
    difficulty: 'INTERMEDIATE',
    summary: 'Cena isométrica estilo render 3D com o produto em um mini cenário lúdico.',
    description: 'Ideal para apps, SaaS, fintechs e produtos digitais: um diorama isométrico que explica o produto com leveza.',
    mediaType: 'THREE_D',
    aspectRatio: '1:1',
    body: 'Isometric 3D diorama of {{cena}}, featuring {{produto}} as the central element. Soft clay render style, rounded shapes, pastel {{paleta}} palette, soft global illumination, gentle ambient occlusion, tiny details that tell a story. Floating on a clean solid background, orthographic camera, high-quality 3D render.',
    variables: [
      { key: 'cena', label: 'Cena', placeholder: 'a tiny home office' },
      { key: 'produto', label: 'Produto', placeholder: 'a smartphone showing a finance app' },
      { key: 'paleta', label: 'Paleta', placeholder: 'lavender and mint', defaultValue: 'soft blue and cream' },
    ],
    parameters: [{ label: 'Midjourney', value: '--ar 1:1 --stylize 200' }],
    expectedResult: 'Ilustração 3D isométrica simpática, útil em landing pages e posts.',
    tips: ['“Clay render” e “soft global illumination” dão o acabamento de render 3D.'],
    tools: ['midjourney', 'chatgpt-gpt-image'],
    tags: ['3d', 'isométrico', 'render', 'saas'],
  },
  {
    slug: 'ugc-style-testimonial-script',
    title: 'UGC Testimonial Script — 30s',
    category: 'conteudo',
    difficulty: 'BEGINNER',
    summary: 'Roteiro de depoimento estilo UGC com gancho, prova e chamada — pronto para gravar ou gerar.',
    description: 'Prompt de texto para criar roteiros de vídeo curto no formato “pessoa real falando para a câmera”. Estruturado em gancho, problema, virada, prova e CTA.',
    mediaType: 'TEXT',
    body: 'Write a 30-second UGC-style testimonial script in Brazilian Portuguese for {{produto}}, aimed at {{publico}}. Structure: 1) Hook in the first 2 seconds that interrupts the scroll; 2) the specific problem I had; 3) the moment I tried the product; 4) one concrete, believable result (no exaggerated claims); 5) a casual call to action: {{cta}}. Tone: spontaneous, conversational, like talking to a friend. Include on-screen text suggestions and B-roll ideas in brackets. Give 3 alternative hooks at the end.',
    variables: [
      { key: 'produto', label: 'Produto', placeholder: 'a posture-correcting office chair' },
      { key: 'publico', label: 'Público', placeholder: 'people who work from home' },
      { key: 'cta', label: 'Chamada', placeholder: 'link na bio com 10% de desconto', defaultValue: 'link na bio' },
    ],
    expectedResult: 'Roteiro de 30s com marcações de texto na tela, sugestões de B-roll e 3 ganchos alternativos.',
    tips: ['Resultado concreto e plausível converte mais que promessa exagerada.', 'Teste os 3 ganchos como variações do mesmo vídeo.'],
    tools: ['chatgpt-gpt-image', 'elevenlabs'],
    tags: ['roteiro', 'ugc', 'tiktok', 'copy'],
    related: ['PROMPT:tiktok-hook-scene-transition'],
  },
  {
    slug: 'tiktok-hook-scene-transition',
    title: 'TikTok Hook — Scene Transition',
    category: 'social-media',
    difficulty: 'ADVANCED',
    summary: 'Transição “impossível” entre dois ambientes para prender a atenção nos primeiros segundos.',
    description: 'Use com quadro inicial e final: a câmera atravessa um objeto e revela outro cenário. Um gancho visual clássico de vídeos de IA que viralizam.',
    mediaType: 'VIDEO',
    aspectRatio: '9:16',
    body: 'Seamless match-cut style transition: the camera pushes rapidly into {{objeto}} in the first scene and emerges on the other side into {{cena_final}}. Continuous forward motion, motion blur during the pass-through, lighting shifts naturally from {{luz_inicial}} to the new environment. Vertical 9:16, energetic, hypnotic, single continuous shot.',
    variables: [
      { key: 'objeto', label: 'Objeto de passagem', placeholder: 'the pupil of a woman’s eye' },
      { key: 'cena_final', label: 'Cena final', placeholder: 'a neon-lit Tokyo street at night' },
      { key: 'luz_inicial', label: 'Luz inicial', placeholder: 'soft daylight', defaultValue: 'soft daylight' },
    ],
    recommendedSettings: [{ label: 'Modo', value: 'Quadro inicial + quadro final (Kling) para controlar as duas cenas' }],
    expectedResult: 'Gancho de 3–5 segundos com transição contínua entre dois mundos.',
    tips: ['Gere as duas imagens antes, com a mesma paleta de luz, e use-as como quadros inicial e final.'],
    tools: ['kling-ai', 'runway'],
    tags: ['tiktok', 'gancho', 'transição', 'viral'],
    related: ['TUTORIAL:animando-imagens-estaticas'],
  },
  {
    slug: 'streetwear-night-lookbook',
    title: 'Streetwear Night Lookbook',
    category: 'moda',
    difficulty: 'INTERMEDIATE',
    summary: 'Lookbook urbano noturno com flash direto, reflexos de rua molhada e atitude.',
    description: 'Estética de campanha streetwear: flash on-camera, cidade à noite e poses espontâneas. Ótimo para marcas jovens e drops.',
    mediaType: 'IMAGE',
    aspectRatio: '4:5',
    body: 'Streetwear lookbook photo of {{modelo}} wearing {{look}}, on a wet city street at night. Direct on-camera flash, hard shadows, reflections of neon signs on the asphalt, slight motion blur in the background. Candid, confident pose, full body, 35mm lens, gritty film texture, youth culture campaign aesthetic.',
    variables: [
      { key: 'modelo', label: 'Modelo', placeholder: 'a tall young man with braids' },
      { key: 'look', label: 'Look', placeholder: 'an oversized black puffer jacket, cargo pants and chunky sneakers' },
    ],
    parameters: [{ label: 'Midjourney', value: '--ar 4:5 --style raw' }],
    expectedResult: 'Foto de lookbook com energia urbana e flash característico.',
    tips: ['“Direct on-camera flash” é o termo-chave desta estética.'],
    tools: ['midjourney'],
    tags: ['moda', 'streetwear', 'noite', 'lookbook'],
    related: ['REFERENCE:neon-noir-urbano-esportivo', 'REFERENCE:filme-35mm-com-grao'],
  },
]
