import type { ContentBundleInput } from '../src/lib/content-bundle'

/**
 * Referências: direções visuais da curadoria INTELRA (paleta, luz, composição, notas).
 * Imagens reais podem ser adicionadas pelo admin (URL de capa) quando houver direitos de uso.
 */
export const references: NonNullable<ContentBundleInput['references']> = [
  {
    slug: 'chiaroscuro-para-perfumaria-de-luxo',
    title: 'Chiaroscuro para perfumaria de luxo',
    category: 'produtos',
    featured: true,
    summary: 'Contraste extremo entre luz e sombra para produtos de vidro e metal.',
    description: 'Uma direção que vem da pintura barroca aplicada à publicidade: fundo quase preto, um único feixe de luz e reflexos precisos.',
    style: 'Chiaroscuro · Still life publicitário',
    notes: 'Use luz de recorte para desenhar o contorno do vidro. Uma cor de acento (dourado, âmbar) no fundo cria profundidade sem poluir.',
    palette: ['#050505', '#1a1510', '#8a6a2f', '#e2ae3a', '#f4f0e6'],
    aspectRatio: '4:5',
    sourceName: 'Curadoria INTELRA',
    tools: ['midjourney', 'magnific-ai'],
    tags: ['luxo', 'produto', 'estúdio', 'contraste'],
    related: ['PROMPT:luxury-product-photography-studio-campaign'],
  },
  {
    slug: 'neon-noir-urbano-esportivo',
    title: 'Neon noir urbano esportivo',
    category: 'cinematico',
    summary: 'Noite, asfalto molhado e neon frio — energia para marcas esportivas e streetwear.',
    description: 'Estética de cinema noir com cores de néon. Funciona muito bem em vídeo vertical e cenas de ação.',
    style: 'Neon noir · Esportivo',
    notes: 'Contraste entre ciano/azul elétrico e magenta. Reflexos no chão molhado dobram a luz disponível. Fumaça leve dá volume aos feixes.',
    palette: ['#05060a', '#0f1b2d', '#1f6feb', '#7cc4ff', '#ff3d7f'],
    aspectRatio: '9:16',
    sourceName: 'Curadoria INTELRA',
    tools: ['kling-ai', 'midjourney'],
    tags: ['noite', 'neon', 'fitness', 'streetwear'],
    related: ['PROMPT:cinematic-fitness-campaign', 'WORKFLOW:anuncio-completo-para-academia'],
  },
  {
    slug: 'editorial-minimalista-off-white',
    title: 'Editorial minimalista off-white',
    category: 'moda',
    summary: 'Fundo off-white, luz de janela e muito respiro — sofisticação silenciosa.',
    description: 'Direção para moda, beleza e marcas de lifestyle que comunicam qualidade sem excesso.',
    style: 'Minimalismo editorial · Quiet luxury',
    notes: 'Poucos elementos em cena. Sombras suaves e longas. A textura do tecido e da pele fazem o trabalho.',
    palette: ['#f4f0e6', '#e6dfd1', '#c9bca4', '#8c7f6c', '#2b2823'],
    aspectRatio: '4:5',
    sourceName: 'Curadoria INTELRA',
    tools: ['midjourney'],
    tags: ['moda', 'minimalista', 'editorial'],
    related: ['PROMPT:editorial-fashion-portrait', 'WORKFLOW:ensaio-editorial-de-moda-com-ia'],
  },
  {
    slug: 'gastronomia-dark-and-moody',
    title: 'Gastronomia dark & moody',
    category: 'fotografia',
    summary: 'Pratos iluminados por luz lateral baixa sobre madeira escura e fundo em sombra.',
    description: 'A estética mais associada a restaurantes autorais: intimista, quente e apetitosa.',
    style: 'Food photography · Low key',
    notes: 'Luz única de janela a 90°. Vapor e brilho de molho indicam frescor. Fundo com bokeh de velas adiciona calor.',
    palette: ['#0c0907', '#2a1d14', '#6b4a2e', '#c98b4a', '#efe3cf'],
    aspectRatio: '4:5',
    sourceName: 'Curadoria INTELRA',
    tools: ['midjourney'],
    tags: ['gastronomia', 'dark moody', 'restaurante'],
    related: ['PROMPT:luxury-restaurant-campaign'],
  },
  {
    slug: 'brutalismo-solar-para-moda',
    title: 'Brutalismo solar para moda',
    category: 'moda',
    summary: 'Concreto aparente, sol duro e sombras geométricas recortando o corpo.',
    description: 'Arquitetura brutalista como cenário de campanhas de verão e resort.',
    style: 'Brutalismo · Luz dura',
    notes: 'Sol do meio-dia cria sombras gráficas. Cores de roupa saturadas contrastam com o cinza do concreto.',
    palette: ['#bdb6aa', '#8d877c', '#4b4740', '#e85d2a', '#1f3a5f'],
    aspectRatio: '3:4',
    sourceName: 'Curadoria INTELRA',
    tools: ['midjourney'],
    tags: ['moda', 'arquitetura', 'verão'],
  },
  {
    slug: 'produto-em-levitacao',
    title: 'Produto em levitação',
    category: 'criar-anuncios',
    summary: 'Produto flutuando com elementos em suspensão — dinamismo para anúncios.',
    description: 'Ingredientes, gotas ou fragmentos suspensos ao redor do produto comunicam frescor e energia.',
    style: 'Levitação · Commercial',
    notes: 'Escolha elementos que contam o benefício (gotas = hidratação, grãos = sabor). Fundo de cor sólida mantém foco.',
    palette: ['#0b3d2e', '#1f7a5c', '#8fd694', '#f2f7f2', '#ffd166'],
    aspectRatio: '1:1',
    sourceName: 'Curadoria INTELRA',
    tools: ['midjourney', 'chatgpt-gpt-image'],
    tags: ['anúncio', 'produto', 'dinâmico'],
    related: ['PROMPT:ai-product-advertisement-hero-banner'],
  },
  {
    slug: 'filme-35mm-com-grao',
    title: 'Filme 35mm com grão',
    category: 'fotografia',
    summary: 'Cores de película, grão orgânico e imperfeições que tiram o aspecto “de IA”.',
    description: 'Referência de textura para humanizar imagens geradas: grão, halation e leve desfoque de movimento.',
    style: 'Analógico · Kodak Portra',
    notes: 'Termos úteis: “35mm film photograph, Kodak Portra 400, natural grain, slight halation”. Funciona com retrato, moda e lifestyle.',
    palette: ['#2e2a24', '#6f5e4b', '#c2a27c', '#e9d8b8', '#7b8f8a'],
    aspectRatio: '3:2',
    sourceName: 'Curadoria INTELRA',
    tools: ['midjourney', 'krea-ai'],
    tags: ['analógico', 'textura', 'lifestyle'],
    related: ['PROMPT:streetwear-night-lookbook'],
  },
  {
    slug: 'tech-clean-infinity-cove',
    title: 'Tech clean em ciclorama infinito',
    category: '3d',
    summary: 'Fundo infinito claro, sombras suaves e objetos com acabamento de render.',
    description: 'Direção para tecnologia, SaaS e eletrônicos: limpeza, precisão e sensação de produto “premium digital”.',
    style: 'Tech minimal · Render',
    notes: 'Ciclorama sem linha de horizonte. Uma cor de acento viva num detalhe do produto. Sombra de contato suave.',
    palette: ['#f7f8fa', '#e3e7ee', '#aab4c3', '#3f8fd6', '#101418'],
    aspectRatio: '16:9',
    sourceName: 'Curadoria INTELRA',
    tools: ['midjourney', 'chatgpt-gpt-image'],
    tags: ['tecnologia', '3d', 'minimalista'],
    related: ['PROMPT:3d-isometric-product-scene'],
  },
]
