import type { ContentBundleInput } from '../src/lib/content-bundle'

/**
 * Diretório de ferramentas. Preços e recursos mudam com frequência: todos os itens do seed
 * entram como NEEDS_REVIEW (sem data de verificação). Verifique e atualize pelo admin.
 */
export const tools: NonNullable<ContentBundleInput['tools']> = [
  {
    slug: 'midjourney',
    title: 'Midjourney',
    category: 'geracao-de-imagem',
    summary: 'Gerador de imagens com forte senso estético — referência em direção de arte e fotografia estilizada.',
    description:
      'O Midjourney se destaca pela qualidade estética “de fábrica”: luz, composição e textura costumam sair refinadas mesmo com prompts curtos. É a escolha frequente para campanhas, moodboards e imagens-conceito.',
    websiteUrl: 'https://www.midjourney.com',
    pricingStatus: 'PAID',
    pricingNote: 'Planos por assinatura. Confirme valores e limites no site oficial.',
    primaryUse: 'Imagens de campanha, direção de arte e conceitos visuais',
    capabilities: ['Texto para imagem', 'Variações e remix', 'Referência de estilo', 'Referência de personagem/objeto', 'Upscale nativo'],
    supportedMedia: ['IMAGE', 'VIDEO'],
    strengths: ['Estética premium com pouco esforço', 'Ótimo controle de estilo por referência', 'Parâmetros técnicos claros (--ar, --stylize)'],
    limitations: ['Texto dentro da imagem ainda é instável', 'Menos literal que modelos de instrução', 'Uso comercial depende do plano'],
    tags: ['imagem', 'direção de arte', 'campanha'],
    featured: true,
  },
  {
    slug: 'chatgpt-gpt-image',
    title: 'ChatGPT (GPT Image)',
    category: 'geracao-de-imagem',
    summary: 'Geração e edição de imagens por conversa, com ótima aderência a instruções e texto legível.',
    description:
      'A geração de imagens do ChatGPT entende instruções longas e detalhadas, edita imagens enviadas e escreve texto dentro da peça com boa precisão — útil para anúncios, mockups e ajustes iterativos.',
    websiteUrl: 'https://chatgpt.com',
    pricingStatus: 'FREEMIUM',
    pricingNote: 'Há uso gratuito com limites; planos pagos ampliam o acesso. Confirme no site oficial.',
    primaryUse: 'Anúncios com texto, edição por instrução e análise de imagens',
    capabilities: ['Texto para imagem', 'Edição de imagem por instrução', 'Texto legível na imagem', 'Análise de imagens enviadas', 'Roteiros e prompts'],
    supportedMedia: ['IMAGE', 'TEXT'],
    strengths: ['Segue instruções complexas', 'Bom com tipografia', 'Iteração conversacional'],
    limitations: ['Estética pode ser mais “limpa” e menos autoral', 'Limites de uso variam por plano'],
    tags: ['imagem', 'edição', 'texto'],
  },
  {
    slug: 'google-veo',
    title: 'Google Veo',
    category: 'geracao-de-video',
    summary: 'Modelo de vídeo do Google com movimento realista e geração de áudio sincronizado.',
    description:
      'O Veo gera clipes a partir de texto ou imagem com física de movimento convincente e compreensão de linguagem de câmera. Disponível pelos produtos e APIs do Google — a forma de acesso muda com frequência.',
    websiteUrl: 'https://deepmind.google/models/veo/',
    pricingStatus: 'UNKNOWN',
    pricingNote: 'Acesso via produtos e planos do Google. Confirme disponibilidade no Brasil.',
    primaryUse: 'Clipes cinematográficos e cenas com áudio',
    capabilities: ['Texto para vídeo', 'Imagem para vídeo', 'Áudio gerado', 'Linguagem de câmera'],
    supportedMedia: ['VIDEO', 'AUDIO'],
    strengths: ['Movimento natural', 'Entende termos de cinema', 'Áudio no mesmo passo'],
    limitations: ['Clipes curtos', 'Disponibilidade e custo variam por região e plano'],
    tags: ['vídeo', 'cinema'],
  },
  {
    slug: 'runway',
    title: 'Runway',
    category: 'geracao-de-video',
    summary: 'Suíte criativa de vídeo com IA: geração, edição e ferramentas de controle de movimento.',
    description:
      'O Runway reúne geração de vídeo, edição assistida e ferramentas como remoção de fundo e controle de câmera. É forte para quem precisa iterar rápido e combinar geração com edição.',
    websiteUrl: 'https://runwayml.com',
    pricingStatus: 'FREEMIUM',
    pricingNote: 'Créditos gratuitos limitados; planos pagos por créditos.',
    primaryUse: 'Imagem para vídeo e edição criativa',
    capabilities: ['Imagem para vídeo', 'Texto para vídeo', 'Controle de câmera', 'Remoção de fundo', 'Edição de vídeo'],
    supportedMedia: ['VIDEO', 'IMAGE'],
    strengths: ['Ecossistema completo', 'Controles de direção', 'Bom para iteração'],
    limitations: ['Consumo de créditos rápido em alta qualidade', 'Clipes curtos por geração'],
    tags: ['vídeo', 'edição'],
  },
  {
    slug: 'kling-ai',
    title: 'Kling AI',
    category: 'geracao-de-video',
    summary: 'Gerador de vídeo com movimento humano convincente e boa fidelidade à imagem de partida.',
    description:
      'O Kling é muito usado para animar imagens estáticas mantendo o produto ou personagem fiel ao original. Bom equilíbrio entre qualidade de movimento e custo.',
    websiteUrl: 'https://klingai.com',
    pricingStatus: 'FREEMIUM',
    pricingNote: 'Créditos diários gratuitos com limites; planos pagos.',
    primaryUse: 'Animar imagens de produto e pessoas',
    capabilities: ['Imagem para vídeo', 'Texto para vídeo', 'Quadro inicial e final', 'Extensão de clipe'],
    supportedMedia: ['VIDEO'],
    strengths: ['Fidelidade à imagem inicial', 'Movimento corporal natural', 'Quadros inicial/final para transições'],
    limitations: ['Fila pode ser longa no plano gratuito', 'Texto e logos podem deformar'],
    tags: ['vídeo', 'animação', 'produto'],
    featured: true,
  },
  {
    slug: 'magnific-ai',
    title: 'Magnific AI',
    category: 'upscale-e-edicao',
    summary: 'Upscaler criativo que adiciona detalhe e textura ao ampliar imagens.',
    description:
      'Diferente de um upscale tradicional, o Magnific “reimagina” detalhes finos (pele, tecido, materiais). Com os controles certos, transforma uma imagem boa em uma imagem de campanha.',
    websiteUrl: 'https://magnific.ai',
    pricingStatus: 'PAID',
    primaryUse: 'Upscale com ganho de detalhe',
    capabilities: ['Upscale criativo', 'Controle de criatividade e semelhança', 'Relight'],
    supportedMedia: ['IMAGE'],
    strengths: ['Detalhe impressionante', 'Controle fino de criatividade'],
    limitations: ['Criatividade alta pode alterar rostos e logos', 'Custo por uso'],
    tags: ['upscale', 'detalhe'],
  },
  {
    slug: 'topaz-labs',
    title: 'Topaz Labs',
    category: 'upscale-e-edicao',
    summary: 'Upscale, nitidez e redução de ruído fiéis ao original — para fotos e vídeos.',
    description:
      'As ferramentas da Topaz priorizam fidelidade: ampliam, removem ruído e recuperam foco sem inventar conteúdo. Ideais para restauração e para finalizar vídeos gerados por IA.',
    websiteUrl: 'https://www.topazlabs.com',
    pricingStatus: 'PAID',
    primaryUse: 'Restauração, nitidez e upscale fiel',
    capabilities: ['Upscale de foto', 'Upscale de vídeo', 'Redução de ruído', 'Recuperação de foco', 'Interpolação de quadros'],
    supportedMedia: ['IMAGE', 'VIDEO'],
    strengths: ['Fidelidade ao original', 'Processamento local disponível', 'Excelente para vídeo'],
    limitations: ['Exige máquina potente para uso local', 'Menos “criativo” que upscalers generativos'],
    tags: ['upscale', 'restauração', 'vídeo'],
  },
  {
    slug: 'elevenlabs',
    title: 'ElevenLabs',
    category: 'audio-e-voz',
    summary: 'Vozes sintéticas naturais, dublagem e efeitos sonoros por texto.',
    description:
      'A ElevenLabs gera locuções expressivas em português e outros idiomas, clona vozes com autorização e cria efeitos sonoros. Fecha a etapa de áudio de vídeos gerados com IA.',
    websiteUrl: 'https://elevenlabs.io',
    pricingStatus: 'FREEMIUM',
    primaryUse: 'Locução, dublagem e efeitos sonoros',
    capabilities: ['Texto para fala', 'Clonagem de voz', 'Dublagem', 'Efeitos sonoros'],
    supportedMedia: ['AUDIO'],
    strengths: ['Naturalidade em PT-BR', 'Controle de emoção e ritmo'],
    limitations: ['Uso comercial e clonagem dependem do plano e de consentimento'],
    tags: ['áudio', 'voz', 'locução'],
  },
  {
    slug: 'suno',
    title: 'Suno',
    category: 'audio-e-voz',
    summary: 'Geração de músicas completas — com ou sem vocal — a partir de uma descrição.',
    description:
      'O Suno cria trilhas originais para vídeos e anúncios a partir de gênero, clima e andamento. Útil para ter música exclusiva sem depender de bancos de áudio.',
    websiteUrl: 'https://suno.com',
    pricingStatus: 'FREEMIUM',
    pricingNote: 'Direitos de uso comercial variam por plano. Confirme antes de usar em campanhas.',
    primaryUse: 'Trilhas originais para vídeos',
    capabilities: ['Música por texto', 'Instrumental', 'Letra e vocal', 'Extensão de faixa'],
    supportedMedia: ['AUDIO'],
    strengths: ['Rapidez', 'Variedade de gêneros'],
    limitations: ['Controle fino de mixagem limitado', 'Licenciamento depende do plano'],
    tags: ['áudio', 'música', 'trilha'],
  },
  {
    slug: 'capcut',
    title: 'CapCut',
    category: 'edicao-de-video',
    summary: 'Editor de vídeo para formatos verticais, com legendas automáticas e recursos de IA.',
    description:
      'O CapCut é o editor mais comum para Reels e TikTok: cortes rápidos, legendas automáticas, templates e ajustes de cor. Onde os clipes gerados por IA viram um vídeo final.',
    websiteUrl: 'https://www.capcut.com',
    pricingStatus: 'FREEMIUM',
    primaryUse: 'Edição final para Reels, TikTok e Shorts',
    capabilities: ['Edição multipista', 'Legendas automáticas', 'Templates', 'Remoção de fundo', 'Correção de cor'],
    supportedMedia: ['VIDEO', 'AUDIO'],
    strengths: ['Curva de aprendizado baixa', 'Feito para vertical', 'Desktop e celular'],
    limitations: ['Alguns recursos exigem assinatura', 'Menos preciso que editores profissionais'],
    tags: ['edição', 'vídeo', 'social media'],
  },
  {
    slug: 'krea-ai',
    title: 'Krea AI',
    category: 'geracao-de-imagem',
    summary: 'Plataforma que reúne vários modelos de imagem e vídeo com geração em tempo real.',
    description:
      'A Krea agrega modelos de diferentes laboratórios num só lugar, com canvas em tempo real e ferramentas de upscale. Boa para comparar modelos e explorar ideias rapidamente.',
    websiteUrl: 'https://www.krea.ai',
    pricingStatus: 'FREEMIUM',
    primaryUse: 'Exploração rápida e comparação de modelos',
    capabilities: ['Geração em tempo real', 'Múltiplos modelos', 'Upscale', 'Imagem para vídeo'],
    supportedMedia: ['IMAGE', 'VIDEO'],
    strengths: ['Vários modelos num lugar', 'Iteração visual instantânea'],
    limitations: ['Qualidade depende do modelo escolhido', 'Créditos compartilhados'],
    tags: ['imagem', 'exploração'],
  },
  {
    slug: 'ideogram',
    title: 'Ideogram',
    category: 'geracao-de-imagem',
    summary: 'Gerador de imagens reconhecido pela tipografia precisa — ótimo para posters e peças com texto.',
    description:
      'O Ideogram renderiza letras e palavras com consistência, o que o torna útil para posters, capas, thumbnails e anúncios com headline dentro da imagem.',
    websiteUrl: 'https://ideogram.ai',
    pricingStatus: 'FREEMIUM',
    primaryUse: 'Peças com tipografia e posters',
    capabilities: ['Texto para imagem', 'Tipografia na imagem', 'Edição por região', 'Estilos predefinidos'],
    supportedMedia: ['IMAGE'],
    strengths: ['Texto legível', 'Bom para layouts gráficos'],
    limitations: ['Fotorrealismo menos consistente que concorrentes especializados'],
    tags: ['imagem', 'tipografia', 'poster'],
  },
]
