import type { ContentBundleInput } from '../src/lib/content-bundle'

export const tutorials: NonNullable<ContentBundleInput['tutorials']> = [
  {
    slug: 'anatomia-de-um-prompt-de-imagem',
    title: 'Anatomia de um prompt de imagem',
    category: 'criar-imagens',
    difficulty: 'BEGINNER',
    featured: true,
    summary: 'Os blocos que todo bom prompt tem — e em que ordem escrevê-los.',
    description: 'Entenda por que alguns prompts funcionam e outros não. Este é o ponto de partida do Lab e a base do Prompt Builder.',
    objective: 'Escrever prompts claros, com assunto, estilo, luz, câmera e acabamento.',
    estimatedMinutes: 12,
    prerequisites: ['Nenhum — comece por aqui'],
    tools: ['midjourney', 'chatgpt-gpt-image'],
    steps: [
      { title: 'Comece pelo assunto', body: 'Diga o que está em cena com substantivos concretos. “Garrafa de perfume preta fosca com tampa dourada” é melhor que “um perfume bonito”.' },
      { title: 'Defina o estilo', body: 'Fotografia publicitária, editorial de moda, render 3D, still de cinema… O estilo muda tudo o que vem depois.' },
      { title: 'Descreva luz e câmera', body: 'Luz (direção, dureza, cor) e câmera (lente, ângulo, profundidade de campo) são o que separa uma imagem amadora de uma profissional.' },
      { title: 'Feche com atmosfera e acabamento', body: 'Humor da cena e qualidade técnica. Evite empilhar adjetivos genéricos como “beautiful, amazing, 8k” sem contexto.' },
      { title: 'Use o negativo com moderação', body: 'O prompt negativo remove problemas específicos (texto, marca d’água, dedos extras). Não use para “desejos”.', prompt: 'luxury-product-photography-studio-campaign' },
    ],
    mistakes: ['Prompts vagos (“uma imagem incrível de…”)', 'Contradições (luz dura e suave ao mesmo tempo)', 'Excesso de palavras de qualidade sem descrever a cena'],
    proTips: ['Escreva como um diretor de fotografia descreveria o set.', 'Mude uma variável por vez ao iterar — assim você aprende o que cada termo faz.', 'Salve as versões que funcionaram no Meu Lab.'],
    tags: ['fundamentos', 'prompt', 'iniciante'],
  },
  {
    slug: 'iluminacao-para-fotografia-de-produto-com-ia',
    title: 'Iluminação para fotografia de produto com IA',
    category: 'produtos',
    difficulty: 'INTERMEDIATE',
    summary: 'Luz de recorte, key light, preenchimento e reflexos: o vocabulário que faz o produto brilhar.',
    description: 'Aprenda os esquemas de luz de estúdio e como descrevê-los para a IA reproduzir.',
    objective: 'Controlar a luz em imagens de produto por meio do prompt.',
    estimatedMinutes: 20,
    prerequisites: ['Anatomia de um prompt de imagem'],
    tools: ['midjourney', 'magnific-ai'],
    steps: [
      { title: 'Key light', body: 'A luz principal define o volume. “Soft key light from the upper left” gera sombras suaves e direção clara.' },
      { title: 'Rim light', body: 'A luz de recorte vem de trás e desenha o contorno — essencial para vidro, metal e produtos escuros.' },
      { title: 'Reflexos controlados', body: 'Peça “controlled specular highlights” e descreva o material. Reflexos são o que dizem “premium”.' },
      { title: 'Cor da luz', body: 'Um acento de cor no fundo (gold, amber, teal) cria profundidade sem mudar o produto.', prompt: 'luxury-product-photography-studio-campaign' },
    ],
    mistakes: ['Pedir “good lighting” sem direção', 'Misturar muitas cores de luz', 'Esquecer o material do produto'],
    proTips: ['Produtos escuros pedem rim light; produtos claros pedem fundo escuro.', 'Faça upscale com criatividade baixa para não alterar os reflexos.'],
    tags: ['iluminação', 'produto', 'estúdio'],
    related: ['REFERENCE:chiaroscuro-para-perfumaria-de-luxo'],
  },
  {
    slug: 'consistencia-de-personagem-e-produto',
    title: 'Consistência de personagem e produto',
    category: 'criar-imagens',
    difficulty: 'ADVANCED',
    summary: 'Como manter o mesmo rosto e o mesmo produto em várias imagens e vídeos.',
    description: 'A consistência é o maior desafio de campanhas com IA. Veja as técnicas que funcionam hoje.',
    objective: 'Produzir séries de imagens com identidade visual estável.',
    estimatedMinutes: 25,
    prerequisites: ['Anatomia de um prompt de imagem'],
    tools: ['midjourney', 'chatgpt-gpt-image', 'kling-ai'],
    steps: [
      { title: 'Crie a imagem-mestre', body: 'Gere uma imagem limpa, de frente, com boa luz. Ela será a referência de todas as outras.' },
      { title: 'Use referência de personagem/objeto', body: 'Ferramentas como o Midjourney aceitam uma imagem de referência de personagem. Ajuste o peso para controlar a fidelidade.' },
      { title: 'Fixe o “DNA” do prompt', body: 'Mantenha idêntico o trecho que descreve pessoa, luz e paleta. Varie só pose, cenário e ação.' },
      { title: 'Anime a partir da imagem', body: 'Em vídeo, sempre parta de uma imagem (image-to-video) em vez de gerar do texto.' },
    ],
    mistakes: ['Reescrever a descrição da pessoa a cada prompt', 'Usar referências com luz muito diferente'],
    proTips: ['Guarde o “DNA” do prompt como um prompt próprio no Meu Lab.', 'Corrija detalhes finais com edição por instrução.'],
    tags: ['consistência', 'personagem', 'avançado'],
    related: ['WORKFLOW:ensaio-editorial-de-moda-com-ia'],
  },
  {
    slug: 'animando-imagens-estaticas',
    title: 'Animando imagens estáticas (image-to-video)',
    category: 'criar-videos',
    difficulty: 'INTERMEDIATE',
    featured: true,
    summary: 'Transforme uma imagem em um clipe crível: movimento, câmera e o que evitar.',
    description: 'Image-to-video é a técnica mais usada no Lab. Entenda como escrever o prompt de movimento e controlar a intensidade.',
    objective: 'Gerar clipes de 5s estáveis a partir de imagens.',
    estimatedMinutes: 18,
    prerequisites: ['Uma imagem de boa qualidade para animar'],
    tools: ['kling-ai', 'runway', 'google-veo'],
    steps: [
      { title: 'Escolha a imagem certa', body: 'Imagens com sujeito claro e fundo simples animam melhor. Faça upscale antes.' },
      { title: 'Descreva só o movimento', body: 'O conteúdo já está na imagem. O prompt deve dizer o que se move e como a câmera se comporta.', prompt: 'product-360-turntable-video' },
      { title: 'Controle a intensidade', body: 'Movimento alto gera deformação. Comece baixo e aumente só se necessário.' },
      { title: 'Use quadros inicial e final', body: 'Para transições, forneça as duas imagens e deixe a IA criar o caminho entre elas.', prompt: 'tiktok-hook-scene-transition' },
    ],
    mistakes: ['Reescrever a cena inteira no prompt de vídeo', 'Movimentos múltiplos num clipe curto', 'Animar imagens de baixa resolução'],
    proTips: ['Uma ação por clipe; o ritmo vem da edição.', 'Gere 2–3 variações e escolha o take mais estável.'],
    tags: ['vídeo', 'animação', 'image-to-video'],
    related: ['WORKFLOW:foto-de-produto-para-video-comercial'],
  },
  {
    slug: 'upscale-sem-artefatos',
    title: 'Upscale sem artefatos',
    category: 'melhorar-fotos',
    difficulty: 'INTERMEDIATE',
    summary: 'Quando usar upscale fiel ou criativo — e como não estragar rostos e logos.',
    description: 'Upscalers generativos inventam detalhes. Aprenda a escolher a ferramenta e os controles certos para cada caso.',
    objective: 'Ampliar imagens mantendo fidelidade e ganhando detalhe.',
    estimatedMinutes: 15,
    prerequisites: [],
    tools: ['magnific-ai', 'topaz-labs'],
    steps: [
      { title: 'Fiel ou criativo?', body: 'Fotos reais e rostos: comece com upscale fiel (Topaz). Imagens geradas: upscale criativo (Magnific) pode adicionar textura.' },
      { title: 'Criatividade baixa primeiro', body: 'Suba a criatividade aos poucos. Acima de 3, rostos e textos tendem a mudar.' },
      { title: 'Compare pontos críticos', body: 'Olhos, dentes, mãos, logos e texto. Se mudaram, volte um nível.' },
    ],
    mistakes: ['Criatividade alta em fotos de pessoas reais', 'Upscale repetido várias vezes'],
    proTips: ['Faça upscale antes de animar em vídeo.', 'Combine: fiel para estrutura, criativo com máscara só onde precisa de textura.'],
    tags: ['upscale', 'restauração', 'qualidade'],
    related: ['WORKFLOW:restauracao-e-melhoria-de-fotos', 'PROMPT:before-after-image-enhancement'],
  },
  {
    slug: 'direcao-de-camera-em-video-com-ia',
    title: 'Direção de câmera em vídeo com IA',
    category: 'cinematico',
    difficulty: 'EXPERT',
    summary: 'Planos, movimentos e lentes: fale a língua do cinema para dirigir modelos de vídeo.',
    description: 'Os modelos de vídeo entendem termos de cinema. Dominar esse vocabulário é o que dá aparência de produção profissional.',
    objective: 'Especificar enquadramento, movimento e lente com precisão.',
    estimatedMinutes: 30,
    prerequisites: ['Animando imagens estáticas'],
    tools: ['google-veo', 'runway', 'kling-ai'],
    steps: [
      { title: 'Planos', body: 'Close, plano médio, plano aberto, plano de ambientação. Diga o plano no início do prompt.' },
      { title: 'Movimentos', body: 'Push-in, pull-out, dolly lateral, travelling, crane, handheld, órbita. Um movimento por clipe.', prompt: 'cinematic-drone-establishing-shot' },
      { title: 'Lentes e profundidade', body: 'Grande angular dramatiza espaço; tele comprime e isola. “Shallow depth of field” separa o sujeito.' },
      { title: 'Ritmo e velocidade', body: 'Câmera lenta aumenta a percepção de qualidade e reduz deformações em ação.', prompt: 'cinematic-fitness-campaign' },
    ],
    mistakes: ['Combinar movimentos de câmera opostos', 'Esquecer de dizer se a câmera está parada'],
    proTips: ['“Camera locked off” evita movimentos indesejados.', 'Planeje a sequência como storyboard antes de gerar.'],
    tags: ['cinema', 'câmera', 'vídeo', 'expert'],
    related: ['WORKFLOW:anuncio-completo-para-academia', 'REFERENCE:neon-noir-urbano-esportivo'],
  },
]
