import type { ContentBundleInput } from '../src/lib/content-bundle'

export const workflows: NonNullable<ContentBundleInput['workflows']> = [
  {
    slug: 'foto-de-produto-para-video-comercial',
    title: 'Foto de produto → vídeo comercial',
    category: 'produtos',
    difficulty: 'INTERMEDIATE',
    featured: true,
    summary: 'Transforme uma foto simples de celular em um vídeo comercial de 15 segundos com trilha e acabamento.',
    description:
      'O fluxo completo mais pedido por marcas: partir da foto real do produto, gerar imagens de campanha fiéis a ele, animar, sonorizar e editar. Cada etapa indica a ferramenta e o prompt.',
    objective: 'Sair de uma foto de celular e chegar a um vídeo vertical de 15s pronto para anúncio.',
    estimatedMinutes: 90,
    inputs: ['Foto do produto em boa luz (fundo neutro ajuda)', 'Nome e principal benefício do produto', 'Cor/identidade da marca'],
    expectedOutput: 'Vídeo 9:16 de ~15 segundos com 3 a 4 cenas, trilha original e acabamento de marca.',
    requiredTools: ['chatgpt-gpt-image', 'midjourney', 'kling-ai', 'capcut'],
    optionalTools: ['magnific-ai', 'suno', 'elevenlabs'],
    steps: [
      {
        title: 'Foto',
        description: 'Fotografe o produto de frente, com luz de janela e fundo liso. Quanto melhor a foto, mais fiel será o resultado.',
        tip: 'Limpe o produto e evite reflexos fortes no rótulo.',
      },
      {
        title: 'Análise da imagem',
        description: 'Envie a foto ao ChatGPT e peça uma descrição técnica do produto (forma, materiais, cores, rótulo). Essa descrição alimenta os próximos prompts.',
        tool: 'chatgpt-gpt-image',
        settings: 'Peça: “Descreva este produto como um fotógrafo publicitário, em inglês, em até 60 palavras.”',
      },
      {
        title: 'Geração de imagens de campanha',
        description: 'Gere 3 cenas diferentes usando a descrição e a foto como referência: hero em estúdio, detalhe macro e contexto de uso.',
        tool: 'midjourney',
        prompt: 'luxury-product-photography-studio-campaign',
        settings: '--ar 9:16 · use a foto real como referência de imagem',
        tip: 'Mantenha a mesma luz e paleta nas três cenas para o vídeo parecer uma campanha única.',
      },
      {
        title: 'Upscale',
        description: 'Amplie as imagens escolhidas antes de animar — o vídeo herda a nitidez da imagem inicial.',
        tool: 'magnific-ai',
        settings: 'Criatividade 0–1 · semelhança alta',
      },
      {
        title: 'Animação em vídeo',
        description: 'Anime cada imagem com movimentos sutis: giro, push-in da câmera, luz deslizando.',
        tool: 'kling-ai',
        prompt: 'product-360-turntable-video',
        settings: '5s por clipe · movimento baixo',
      },
      {
        title: 'Som',
        description: 'Crie uma trilha curta no clima da marca e, se quiser, uma locução com o benefício principal.',
        tool: 'suno',
        settings: 'Instrumental, 15–20s, andamento médio',
      },
      {
        title: 'Edição final',
        description: 'Monte os clipes no ritmo da trilha, adicione logo, headline e CTA nos 3 segundos finais.',
        tool: 'capcut',
        tip: 'Coloque o produto nos 2 primeiros segundos — é o que segura o scroll.',
      },
    ],
    alternatives: ['Runway no lugar do Kling para animação', 'GPT Image no lugar do Midjourney quando precisar de texto na imagem'],
    troubleshooting: [
      { problem: 'O rótulo deforma no vídeo', solution: 'Reduza o movimento, use clipes mais curtos e aplique o rótulo real por cima na edição.' },
      { problem: 'As cenas parecem de campanhas diferentes', solution: 'Fixe paleta e luz no prompt e use a mesma referência de estilo em todas.' },
      { problem: 'Imagem perde detalhe ao animar', solution: 'Faça o upscale antes da animação e exporte em alta qualidade.' },
    ],
    tags: ['produto', 'vídeo', 'e-commerce', 'anúncio'],
    related: ['REFERENCE:chiaroscuro-para-perfumaria-de-luxo', 'TUTORIAL:animando-imagens-estaticas'],
  },
  {
    slug: 'anuncio-completo-para-academia',
    title: 'Anúncio completo para academia',
    category: 'criar-anuncios',
    difficulty: 'ADVANCED',
    featured: true,
    summary: 'Da referência ao anúncio final: direção criativa, cenas cinematográficas, locução e edição para academias.',
    description:
      'Exemplo do caminho INTELRA: referência → direção criativa → ferramenta → prompt → workflow → execução. Um anúncio de 20 segundos com cara de marca esportiva grande.',
    objective: 'Produzir um anúncio vertical de 20s para uma academia, com energia de marca esportiva.',
    estimatedMinutes: 180,
    inputs: ['Nome e diferencial da academia', 'Oferta (ex.: primeira semana grátis)', 'Fotos do espaço (opcional, para referência)'],
    expectedOutput: 'Anúncio 9:16 de ~20s com 4 cenas, locução, trilha e CTA.',
    requiredTools: ['midjourney', 'kling-ai', 'elevenlabs', 'capcut'],
    optionalTools: ['google-veo', 'suno', 'chatgpt-gpt-image'],
    steps: [
      { title: 'Referência', description: 'Escolha a direção visual. Neon noir para energia noturna; luz dura e suor para intensidade.', tip: 'Veja a referência “Neon noir urbano esportivo”.' },
      { title: 'Direção criativa', description: 'Defina conceito, 4 cenas e frase final. Ex.: “Cada repetição conta”. Peça ao ChatGPT 3 conceitos e escolha 1.', tool: 'chatgpt-gpt-image' },
      { title: 'Frames das cenas', description: 'Gere uma imagem por cena com o mesmo atleta e a mesma luz.', tool: 'midjourney', settings: '--ar 9:16 · referência de personagem' },
      { title: 'Animação', description: 'Anime cada frame com o prompt cinematográfico, uma ação por clipe.', tool: 'kling-ai', prompt: 'cinematic-fitness-campaign', settings: '5s · movimento médio' },
      { title: 'Locução', description: 'Grave a frase-conceito e a oferta com voz firme e ritmo curto.', tool: 'elevenlabs', settings: 'Estabilidade média · estilo alto' },
      { title: 'Edição e CTA', description: 'Corte no ritmo da trilha, legendas grandes e oferta nos 4 segundos finais.', tool: 'capcut' },
    ],
    alternatives: ['Google Veo para cenas com áudio ambiente gerado', 'Suno para trilha original em vez de banco de músicas'],
    troubleshooting: [
      { problem: 'O atleta muda de rosto entre cenas', solution: 'Use referência de personagem e gere todas as cenas a partir da mesma imagem-base.' },
      { problem: 'Membros deformam no movimento', solution: 'Diminua a intensidade de movimento e prefira ações lentas (câmera lenta ajuda).' },
    ],
    tags: ['fitness', 'academia', 'anúncio', 'vídeo', 'locução'],
    related: ['REFERENCE:neon-noir-urbano-esportivo', 'TUTORIAL:direcao-de-camera-em-video-com-ia'],
  },
  {
    slug: 'ensaio-editorial-de-moda-com-ia',
    title: 'Ensaio editorial de moda com IA',
    category: 'moda',
    difficulty: 'INTERMEDIATE',
    summary: 'Crie um ensaio de 6 fotos coerente para lookbook ou lançamento de coleção.',
    description: 'Produção de ensaio com consistência de modelo, luz e cenário — o desafio central da moda com IA.',
    objective: 'Gerar 6 imagens de um mesmo ensaio, com modelo e estética consistentes.',
    estimatedMinutes: 120,
    inputs: ['Peças da coleção (fotos flat-lay ou no manequim)', 'Conceito da coleção', 'Paleta'],
    expectedOutput: 'Série de 6 imagens editoriais em 4:5, prontas para lookbook.',
    requiredTools: ['midjourney', 'magnific-ai'],
    optionalTools: ['chatgpt-gpt-image'],
    steps: [
      { title: 'Conceito e casting', description: 'Defina o conceito e gere a modelo principal. Salve a imagem como referência de personagem.', tool: 'midjourney' },
      { title: 'Cenário e luz', description: 'Fixe fundo e luz: repita exatamente o mesmo trecho em todos os prompts.', prompt: 'editorial-fashion-portrait' },
      { title: 'Variações de pose e look', description: 'Troque apenas o look e a pose a cada imagem.', tool: 'midjourney', settings: '--ar 4:5 --style raw · referência de personagem' },
      { title: 'Correção de peças', description: 'Ajuste detalhes da roupa para ficarem fiéis à coleção real.', tool: 'chatgpt-gpt-image' },
      { title: 'Upscale e textura', description: 'Amplie com foco em tecido e pele.', tool: 'magnific-ai', settings: 'Criatividade 1–2' },
    ],
    alternatives: ['Krea para testar vários modelos de imagem no casting'],
    troubleshooting: [{ problem: 'A roupa não bate com a peça real', solution: 'Edite por instrução com a foto da peça como referência e descreva tecido e costuras.' }],
    tags: ['moda', 'editorial', 'lookbook', 'consistência'],
    related: ['REFERENCE:editorial-minimalista-off-white', 'TUTORIAL:consistencia-de-personagem-e-produto'],
  },
  {
    slug: 'lancamento-de-produto-no-instagram',
    title: 'Lançamento de produto no Instagram',
    category: 'social-media',
    difficulty: 'BEGINNER',
    summary: 'Kit de lançamento: carrossel, post de anúncio e Reels curto — tudo com a mesma identidade.',
    description: 'Planeje e produza as peças de um lançamento em uma tarde, com consistência entre formatos.',
    objective: 'Produzir carrossel (5 slides), 1 banner de anúncio e 1 Reels de 10s.',
    estimatedMinutes: 60,
    inputs: ['Foto do produto', 'Data e oferta de lançamento', 'Cores da marca'],
    expectedOutput: 'Pacote de peças coerentes para feed, anúncio e Reels.',
    requiredTools: ['chatgpt-gpt-image', 'midjourney', 'capcut'],
    optionalTools: ['kling-ai', 'ideogram'],
    steps: [
      { title: 'Roteiro do carrossel', description: 'Peça ao ChatGPT a sequência de 5 slides: gancho, problema, produto, prova, CTA.', tool: 'chatgpt-gpt-image' },
      { title: 'Capa do carrossel', description: 'Gere a capa com o produto cortado na borda para induzir o arrasto.', tool: 'midjourney', prompt: 'instagram-product-launch-carousel' },
      { title: 'Banner de anúncio', description: 'Crie o banner com headline legível.', tool: 'chatgpt-gpt-image', prompt: 'ai-product-advertisement-hero-banner' },
      { title: 'Reels curto', description: 'Anime a capa ou o hero e edite com texto na tela.', tool: 'capcut' },
    ],
    alternatives: ['Ideogram para capas com tipografia forte'],
    troubleshooting: [{ problem: 'Texto com erro de ortografia', solution: 'Aplique o texto no editor em vez de gerar dentro da imagem.' }],
    tags: ['instagram', 'lançamento', 'carrossel', 'reels'],
  },
  {
    slug: 'restauracao-e-melhoria-de-fotos',
    title: 'Restauração e melhoria de fotos',
    category: 'melhorar-fotos',
    difficulty: 'BEGINNER',
    summary: 'Recupere fotos antigas ou de celular com fidelidade — e gere o antes e depois para redes sociais.',
    description: 'Fluxo seguro de restauração: primeiro fidelidade, depois detalhe. Evita o erro comum de “trocar” o rosto da pessoa.',
    objective: 'Restaurar uma foto preservando identidade e publicar um antes/depois.',
    estimatedMinutes: 30,
    inputs: ['Foto original (arquivo, não print)'],
    expectedOutput: 'Foto restaurada em alta resolução + vídeo/slide de antes e depois.',
    requiredTools: ['topaz-labs', 'chatgpt-gpt-image'],
    optionalTools: ['magnific-ai', 'capcut'],
    steps: [
      { title: 'Limpeza e nitidez fiel', description: 'Remova ruído e recupere foco sem alterar conteúdo.', tool: 'topaz-labs' },
      { title: 'Correção de luz e cor', description: 'Ajuste balanço de branco e sombras mantendo a pessoa idêntica.', tool: 'chatgpt-gpt-image', prompt: 'before-after-image-enhancement' },
      { title: 'Detalhe final (opcional)', description: 'Adicione textura fina com criatividade mínima.', tool: 'magnific-ai', settings: 'Criatividade 0 · semelhança máxima' },
      { title: 'Antes e depois', description: 'Monte o comparativo com cortina deslizante.', tool: 'capcut' },
    ],
    alternatives: ['Pular o Magnific quando a foto tiver rostos pequenos'],
    troubleshooting: [{ problem: 'O rosto ficou diferente', solution: 'Volte à etapa anterior e reduza criatividade; compare olhos, boca e mãos.' }],
    tags: ['restauração', 'antes e depois', 'upscale'],
    related: ['TUTORIAL:upscale-sem-artefatos'],
  },
  {
    slug: 'campanha-para-restaurante-premium',
    title: 'Campanha para restaurante premium',
    category: 'fotografia',
    difficulty: 'INTERMEDIATE',
    summary: 'Fotos de pratos, ambiente e um vídeo curto de atmosfera para restaurantes de alto padrão.',
    description: 'Produza o material de um lançamento de cardápio ou inauguração com estética dark & moody.',
    objective: 'Criar 5 fotos de pratos, 1 foto de ambiente e 1 vídeo de 10s.',
    estimatedMinutes: 100,
    inputs: ['Fotos reais dos pratos (referência)', 'Nome dos pratos e ingredientes', 'Fotos do salão (opcional)'],
    expectedOutput: 'Kit visual coerente para cardápio digital e Instagram.',
    requiredTools: ['midjourney', 'magnific-ai', 'runway'],
    optionalTools: ['suno', 'capcut'],
    steps: [
      { title: 'Direção visual', description: 'Defina a estética com base na referência dark & moody.' },
      { title: 'Pratos', description: 'Gere cada prato com a foto real como referência.', tool: 'midjourney', prompt: 'luxury-restaurant-campaign' },
      { title: 'Detalhe', description: 'Upscale com foco em textura dos alimentos.', tool: 'magnific-ai' },
      { title: 'Vídeo de atmosfera', description: 'Anime vapor, velas e movimento lento de câmera.', tool: 'runway', settings: 'Movimento baixo · 5s' },
      { title: 'Montagem', description: 'Junte com trilha suave para Reels.', tool: 'capcut' },
    ],
    alternatives: ['Kling para a animação dos pratos'],
    troubleshooting: [{ problem: 'Comida com aparência artificial', solution: 'Descreva texturas (crocante, brilho do molho) e reduza a estilização.' }],
    tags: ['gastronomia', 'restaurante', 'campanha'],
    related: ['REFERENCE:gastronomia-dark-and-moody'],
  },
]
